[package]
name = "private-storage-proof"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# halo2-base = { default-features = false, features = [
#     "halo2-pse",
# ], git = "https://github.com/axiom-crypto/halo2-lib.git" }
# axiom-eth = { git = "https://github.com/axiom-crypto/axiom-eth.git", features = [
#     "evm",
#     "halo2-axiom",
#     "providers",
# ] }
axiom-eth = { path = "./axiom-eth/axiom-eth", features = [
    "evm",
    "halo2-axiom",
    "providers",
] }
serde_json = "1.0.120"
ethers-core = { version = "=2.0.14", features = ["optimism"] }
ethers-providers = { version = "=2.0.14", optional = true, features = [
    "optimism",
] }
